{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-orm",
    "version": "5.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gt2f75atzvb23pcglcp5g2jjzy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.2"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.2"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.3.2"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.2"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-orm-5.3.2.jar",
          "url": "spring-orm-5.3.2.jar",
          "size": 200261,
          "sha512": "09649c9361006f6abf1cc805c07f58167c7864e7365880cd94496bd30b91e6b3920d6f53cd2c325e06daab27001873586a628e4909ab071d43c0e4dfdab98df8",
          "sha256": "34740b1be0cdf0427514b69bb064618a080751c0d6453a34174d04e14bd010f4",
          "sha1": "ce3d41f6a4f0f26c41171299888c49e020e4f443",
          "md5": "12e7667b11fde31e8f5e94413822f2a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.2"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.2"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.3.2"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.2"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-orm-5.3.2.jar",
          "url": "spring-orm-5.3.2.jar",
          "size": 200261,
          "sha512": "09649c9361006f6abf1cc805c07f58167c7864e7365880cd94496bd30b91e6b3920d6f53cd2c325e06daab27001873586a628e4909ab071d43c0e4dfdab98df8",
          "sha256": "34740b1be0cdf0427514b69bb064618a080751c0d6453a34174d04e14bd010f4",
          "sha1": "ce3d41f6a4f0f26c41171299888c49e020e4f443",
          "md5": "12e7667b11fde31e8f5e94413822f2a6"
        }
      ]
    }
  ]
}
