{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-jpa",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "vbd2bptt75f37pnxw4wotn6inu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.4.25.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.4.2"
          },
          "excludes": [
            {
              "group": "org.aspectj",
              "module": "aspectjrt"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.4.1.jar",
          "url": "spring-boot-starter-data-jpa-2.4.1.jar",
          "size": 4758,
          "sha512": "95688965672224cb60a3fbaa8923ab6d322a7fd4019baa6d6a7bb3df775964073a9ae76c532d29e37f0648d07b61c2559a3095a1131c01e35828c2388597299a",
          "sha256": "3c70bfc25fa0250558743d6ff889ebcc564f3dabbb5d1cb3c81a498345cf3ad9",
          "sha1": "7801874040c4c3050ebd4b5fee572f72e26219b0",
          "md5": "f07541bcf0021392569cdcff68ecf51b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.4.25.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.4.2"
          },
          "excludes": [
            {
              "group": "org.aspectj",
              "module": "aspectjrt"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.4.1.jar",
          "url": "spring-boot-starter-data-jpa-2.4.1.jar",
          "size": 4758,
          "sha512": "95688965672224cb60a3fbaa8923ab6d322a7fd4019baa6d6a7bb3df775964073a9ae76c532d29e37f0648d07b61c2559a3095a1131c01e35828c2388597299a",
          "sha256": "3c70bfc25fa0250558743d6ff889ebcc564f3dabbb5d1cb3c81a498345cf3ad9",
          "sha1": "7801874040c4c3050ebd4b5fee572f72e26219b0",
          "md5": "f07541bcf0021392569cdcff68ecf51b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.4.1-javadoc.jar",
          "url": "spring-boot-starter-data-jpa-2.4.1-javadoc.jar",
          "size": 4749,
          "sha512": "59fc1598e25d326e1e3b436d03c6a37f01391cd29dd5cf50dda4b065e67d67639860edca609e4a67a43059811ddb93da8d7e4ef36e29e8586eb99c5b89e55e82",
          "sha256": "1231955182e355530f71de3dc0909e5cb76e8eea7739539f31dbeaf86ce9333f",
          "sha1": "64550c4272050270f470d5aa83ef2dd327633f64",
          "md5": "17c8af69a3ebffd139387b8df342b574"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.4.1-sources.jar",
          "url": "spring-boot-starter-data-jpa-2.4.1-sources.jar",
          "size": 4747,
          "sha512": "33c3d2334a91da98874e579d874d45727fe2a48d7b1ccbbf4cf71d546e18e916af4b38173dbb4185719a81248c41277f8ad2215ad0b8a29970e88f4bd62f2d49",
          "sha256": "4741d77d0d49faef3d203ca0cf61ecadbaa42ed6ce6c902e564989b45d3216f5",
          "sha1": "a2b5fad66afdb86cae63a57387044dc04fe8f415",
          "md5": "cf8e6f4d3a601db35f2d1f8370d6b3f9"
        }
      ]
    }
  ]
}
