{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter",
    "version": "5.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "nl5ignh23jdd7pqfnyu5j6hawe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-params",
          "version": {
            "requires": "5.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-5.7.0.jar",
          "url": "junit-jupiter-5.7.0.jar",
          "size": 6359,
          "sha512": "63637c6c95afb44456bae60286c635b876b36c63271c93e882e78467c03824eba4321c30edf550a81697a4968f14561c049752d4c1403bafaf205e29b2ed5182",
          "sha256": "f15ebc08c85be1f46cd2aff06d6125e5083da0f527cd434f8b5431b5b0a1abd0",
          "sha1": "3152d152da916ccbb0715f89f7f873f45362ad7f",
          "md5": "8226e205f4dec37ddda94bdb86d148dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-params",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-5.7.0.jar",
          "url": "junit-jupiter-5.7.0.jar",
          "size": 6359,
          "sha512": "63637c6c95afb44456bae60286c635b876b36c63271c93e882e78467c03824eba4321c30edf550a81697a4968f14561c049752d4c1403bafaf205e29b2ed5182",
          "sha256": "f15ebc08c85be1f46cd2aff06d6125e5083da0f527cd434f8b5431b5b0a1abd0",
          "sha1": "3152d152da916ccbb0715f89f7f873f45362ad7f",
          "md5": "8226e205f4dec37ddda94bdb86d148dd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-5.7.0-javadoc.jar",
          "url": "junit-jupiter-5.7.0-javadoc.jar",
          "size": 5681,
          "sha512": "1fae01f45210a2a2a4f67b91eddda48f1d238140a97c49ec9f0d7311679ad4af48265273e5efcefa2f311ccf2e0653ccc76af9050f0807a8fded566d99178fea",
          "sha256": "87e2e56e44d1ce3a882eff2bed179ea74a27cbcbd888f13536c413a87d32f58a",
          "sha1": "3c791495768512669e0463f7be775c1ee4ea10c3",
          "md5": "6c7369516c034cf85e6adbce4a9ed291"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-5.7.0-sources.jar",
          "url": "junit-jupiter-5.7.0-sources.jar",
          "size": 6091,
          "sha512": "dc317765c2bbc6f6590da9867c9a32dda6b7c6562828124cb746f0d000be7fda496ec9d270f0baa411cb5bce092c92603eb3d8e281cedc8945c94e9a73183830",
          "sha256": "cc1b00b400c73b7c8dafe0ef530e68a104fd478bd3e6359fa3e6a50e513f2c4a",
          "sha1": "7009caa171d1d6af0f6f09dff25f9f574826a490",
          "md5": "25dcc971c68f390a728c2f3fa10d31fa"
        }
      ]
    }
  ]
}
