{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "vbd2bptt75f37pnxw4wotn6inu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.41"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.glassfish",
          "module": "jakarta.el",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.41"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.4.1.jar",
          "url": "spring-boot-starter-tomcat-2.4.1.jar",
          "size": 4796,
          "sha512": "42b9ec83ebb2ef1de362089d2a2388335c744e9e9058b2cc2fc6145a926534206a2a5a937e3ffe9f0dbb0f3ae6808779019488d7184b89892ac2ceac1c850903",
          "sha256": "aff5d77fcb42a4ef01e526188438885e4f01b0d1d62f201b591ff80d70e91efd",
          "sha1": "92c0d7938bdf47fb9d3781aef94b07f5a940a263",
          "md5": "d34981e35722ed342e8e7fdd23d4ea3b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.41"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.glassfish",
          "module": "jakarta.el",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.41"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.4.1.jar",
          "url": "spring-boot-starter-tomcat-2.4.1.jar",
          "size": 4796,
          "sha512": "42b9ec83ebb2ef1de362089d2a2388335c744e9e9058b2cc2fc6145a926534206a2a5a937e3ffe9f0dbb0f3ae6808779019488d7184b89892ac2ceac1c850903",
          "sha256": "aff5d77fcb42a4ef01e526188438885e4f01b0d1d62f201b591ff80d70e91efd",
          "sha1": "92c0d7938bdf47fb9d3781aef94b07f5a940a263",
          "md5": "d34981e35722ed342e8e7fdd23d4ea3b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.4.1-javadoc.jar",
          "url": "spring-boot-starter-tomcat-2.4.1-javadoc.jar",
          "size": 4744,
          "sha512": "f89db931a2b979a8734050f601f8f5d5a7e25e684b4b781c874ea2fc1fc6e7760f225a4cdaf4b2d17f4903e42124c646269aa070d157cf28d27bb5226728baa0",
          "sha256": "383e288d155f5b63b0378c615daa20c6251b97eb4dce281cd65107d600e53404",
          "sha1": "97c18a82d68aa8f92f6dcd2e6934de1109b719a4",
          "md5": "577cdd19efcd55e6027aa0e142604f7e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.4.1-sources.jar",
          "url": "spring-boot-starter-tomcat-2.4.1-sources.jar",
          "size": 4743,
          "sha512": "b4831338a9bf5a9c0780e607f863e324dfbae4d62afdfb605e4734b318a046c94719e7db1bb0d51834073cc7794d0780af633e8cbfb96b5bc70eae646138a092",
          "sha256": "66dc07efc3a346b0c3f7b31248eed4e576b6033d34d6ebf79f306b2403fe8b8d",
          "sha1": "76a8f392ed846ef838d249daf574f69998877a9d",
          "md5": "632ceb4c0d74fe810053a9d5a08fa0d5"
        }
      ]
    }
  ]
}
