{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-expression",
    "version": "5.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gt2f75atzvb23pcglcp5g2jjzy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-5.3.2.jar",
          "url": "spring-expression-5.3.2.jar",
          "size": 282517,
          "sha512": "e67307c5f4902a9d7362d57fc7714849feff8ec260ec14f2077e8948b919427a2333ba3cf638f5f4f206053ba5be8898c233a59d16f122983b7f23da66d130c7",
          "sha256": "0a30b63689c80dcdd04cfbb71aff2b3cb6a960cf33b473636104336334a36ae3",
          "sha1": "31cfebc4f74de54ddf4298cc6fa4de4090486c41",
          "md5": "3e77f4dfb4d5c1780dafa7f37f2eb78d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-5.3.2.jar",
          "url": "spring-expression-5.3.2.jar",
          "size": 282517,
          "sha512": "e67307c5f4902a9d7362d57fc7714849feff8ec260ec14f2077e8948b919427a2333ba3cf638f5f4f206053ba5be8898c233a59d16f122983b7f23da66d130c7",
          "sha256": "0a30b63689c80dcdd04cfbb71aff2b3cb6a960cf33b473636104336334a36ae3",
          "sha1": "31cfebc4f74de54ddf4298cc6fa4de4090486c41",
          "md5": "3e77f4dfb4d5c1780dafa7f37f2eb78d"
        }
      ]
    }
  ]
}
